# Generated by Django 4.2.7 on 2024-02-16 20:03

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(help_text='Required. Enter a valid email address.', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(help_text='Required. Enter your first name.', max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(help_text='Required. Enter your last name.', max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mobile_number',
            field=content.models.MobileNumberField(help_text='Required. Enter your mobile number.'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pincode',
            field=content.models.PinCodeField(help_text='Enter your Pin Code'),
        ),
    ]
