# Generated by Django 4.2.7 on 2024-02-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_customuser_email_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='username',
            field=models.TextField(default='user', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='password',
            field=models.CharField(default='st.1303', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='passkey',
            field=models.CharField(help_text='Required. Enter your password.', max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='default_username', help_text='Required. Enter your username.', max_length=30),
        ),
    ]
