# Generated by Django 4.2.7 on 2024-02-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_blog_username_customuser_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(default='admin', help_text='are you a admin or author', max_length=6),
            preserve_default=False,
        ),
    ]
