# Generated by Django 4.2.7 on 2024-02-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_customuser_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='categories',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='blog',
            name='username',
            field=models.CharField(max_length=60),
        ),
    ]
