# Generated by Django 4.2.7 on 2024-02-18 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_rename_categories_blog_category_alter_blog_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='username',
            new_name='createdBy',
        ),
    ]
