# Generated by Django 4.2.10 on 2024-02-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_rename_username_blog_createdby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='passkey',
            field=models.CharField(help_text='Required. Enter your password.', max_length=100),
        ),
    ]
