# Generated by Django 4.2.10 on 2024-02-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_alter_customuser_passkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='default_username', help_text='Required. Enter your username.', max_length=30, unique=True),
        ),
    ]
