# Generated by Django 4.2.10 on 2024-02-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_alter_blog_title_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('author', 'Author')], help_text='are you a admin or author', max_length=6),
        ),
    ]
